// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/account" | "/admin" | "/admin/articles" | "/admin/articles/edit" | "/admin/articles/new" | "/admin/codes" | "/admin/games" | "/admin/games/edit" | "/admin/games/new" | "/admin/leaks" | "/admin/leaks/edit" | "/admin/leaks/new" | "/admin/login" | "/admin/orders" | "/admin/submissions" | "/admin/users" | "/advertise" | "/analysis" | "/articles/detail" | "/auth" | "/auth/test" | "/calendar" | "/claim" | "/contact" | "/copyright" | "/forum" | "/forum/games" | "/forum/general" | "/forum/leaks" | "/forum/new" | "/forum/off-topic" | "/forum/post" | "/games" | "/games/compare" | "/games/detail" | "/join" | "/leaks" | "/member" | "/member/cancel" | "/member/success" | "/privacy" | "/submit" | "/terms" | "/videos"
type AppRouteHandlerRoutes = "/api/stripe/checkout" | "/api/stripe/portal" | "/api/upload/presign"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/account": {}
  "/admin": {}
  "/admin/articles": {}
  "/admin/articles/edit": {}
  "/admin/articles/new": {}
  "/admin/codes": {}
  "/admin/games": {}
  "/admin/games/edit": {}
  "/admin/games/new": {}
  "/admin/leaks": {}
  "/admin/leaks/edit": {}
  "/admin/leaks/new": {}
  "/admin/login": {}
  "/admin/orders": {}
  "/admin/submissions": {}
  "/admin/users": {}
  "/advertise": {}
  "/analysis": {}
  "/api/stripe/checkout": {}
  "/api/stripe/portal": {}
  "/api/upload/presign": {}
  "/articles/detail": {}
  "/auth": {}
  "/auth/test": {}
  "/calendar": {}
  "/claim": {}
  "/contact": {}
  "/copyright": {}
  "/forum": {}
  "/forum/games": {}
  "/forum/general": {}
  "/forum/leaks": {}
  "/forum/new": {}
  "/forum/off-topic": {}
  "/forum/post": {}
  "/games": {}
  "/games/compare": {}
  "/games/detail": {}
  "/join": {}
  "/leaks": {}
  "/member": {}
  "/member/cancel": {}
  "/member/success": {}
  "/privacy": {}
  "/submit": {}
  "/terms": {}
  "/videos": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
