// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../../src/app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account">> = Specific
  const handler = {} as typeof import("../../../src/app/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/articles/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/articles/edit">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/articles/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/articles/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/articles/new">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/articles/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/articles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/articles">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/articles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/codes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/codes">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/codes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/games/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/games/edit">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/games/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/games/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/games/new">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/games/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/games/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/games">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/games/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/leaks/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/leaks/edit">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/leaks/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/leaks/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/leaks/new">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/leaks/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/leaks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/leaks">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/leaks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/login">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/orders">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/submissions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/submissions">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/submissions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/advertise/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/advertise">> = Specific
  const handler = {} as typeof import("../../../src/app/advertise/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/analysis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analysis">> = Specific
  const handler = {} as typeof import("../../../src/app/analysis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/articles/detail/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/articles/detail">> = Specific
  const handler = {} as typeof import("../../../src/app/articles/detail/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/test/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/test">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/test/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/calendar">> = Specific
  const handler = {} as typeof import("../../../src/app/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/claim/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/claim">> = Specific
  const handler = {} as typeof import("../../../src/app/claim/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../../src/app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/copyright/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/copyright">> = Specific
  const handler = {} as typeof import("../../../src/app/copyright/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/forum/games/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forum/games">> = Specific
  const handler = {} as typeof import("../../../src/app/forum/games/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/forum/general/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forum/general">> = Specific
  const handler = {} as typeof import("../../../src/app/forum/general/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/forum/leaks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forum/leaks">> = Specific
  const handler = {} as typeof import("../../../src/app/forum/leaks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/forum/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forum/new">> = Specific
  const handler = {} as typeof import("../../../src/app/forum/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/forum/off-topic/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forum/off-topic">> = Specific
  const handler = {} as typeof import("../../../src/app/forum/off-topic/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/forum/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forum">> = Specific
  const handler = {} as typeof import("../../../src/app/forum/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/forum/post/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forum/post">> = Specific
  const handler = {} as typeof import("../../../src/app/forum/post/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/games/compare/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/games/compare">> = Specific
  const handler = {} as typeof import("../../../src/app/games/compare/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/games/detail/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/games/detail">> = Specific
  const handler = {} as typeof import("../../../src/app/games/detail/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/games/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/games">> = Specific
  const handler = {} as typeof import("../../../src/app/games/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/join/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/join">> = Specific
  const handler = {} as typeof import("../../../src/app/join/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/leaks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leaks">> = Specific
  const handler = {} as typeof import("../../../src/app/leaks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/member/cancel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/member/cancel">> = Specific
  const handler = {} as typeof import("../../../src/app/member/cancel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/member/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/member">> = Specific
  const handler = {} as typeof import("../../../src/app/member/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/member/success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/member/success">> = Specific
  const handler = {} as typeof import("../../../src/app/member/success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../../src/app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/submit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/submit">> = Specific
  const handler = {} as typeof import("../../../src/app/submit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../../src/app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/videos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/videos">> = Specific
  const handler = {} as typeof import("../../../src/app/videos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/stripe/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/checkout">> = Specific
  const handler = {} as typeof import("../../../src/app/api/stripe/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/stripe/portal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/portal">> = Specific
  const handler = {} as typeof import("../../../src/app/api/stripe/portal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/upload/presign/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload/presign">> = Specific
  const handler = {} as typeof import("../../../src/app/api/upload/presign/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
